<?php

namespace EmizorIpx\ClientFel\Utils;

class InvoiceStates{
    const INVOICE_STATE_IN_QUEUE = "INVOICE_STATE_IN_QUEUE";
    const INVOICE_STATE_SENT_TO_SIN = "INVOICE_STATE_SENT_TO_SIN";
    const INVOICE_STATE_SENT_TO_SIN_INVALID = "INVOICE_STATE_SENT_TO_SIN_INVALID";
    const INVOICE_STATE_SIN_VALID = "INVOICE_STATE_SIN_VALID";
    const INVOICE_STATE_SIN_INVALID = "INVOICE_STATE_SIN_INVALID";
    const INVOICE_STATE_INTERNAL_ERROR = "INVOICE_STATE_INTERNAL_ERROR";
    const INVOICE_STATE_QUEUE_PENDING = "INVOICE_STATE_QUEUE_PENDING";
    const INVOICE_STATE_QUEUE_PENDING_CUF = "INVOICE_STATE_QUEUE_PENDING_CUF";

    const INVOICE_REVOCATION_STATE_SIN_VALID = "INVOICE_REVOCATION_STATE_SIN_VALID";
    const INVOICE_REVOCATION_STATE_IN_QUEUE = "INVOICE_REVOCATION_STATE_IN_QUEUE";
    const INVOICE_REVOCATION_STATE_SENT_TO_SIN = "INVOICE_REVOCATION_STATE_SENT_TO_SIN";
    const INVOICE_REVOCATION_STATE_SENT_TO_SIN_INVALID = "INVOICE_REVOCATION_STATE_SENT_TO_SIN_INVALID";
    const INVOICE_REVOCATION_STATE_SIN_INVALID = "INVOICE_REVOCATION_STATE_SIN_INVALID";
    const INVOICE_REVOCATION_STATE_INTERNAL_ERROR = "INVOICE_REVOCATION_STATE_INTERNAL_ERROR";


    const INVOICE_REVERSION_STATE_QUEUE_PENDING = "INVOICE_REVERSION_STATE_QUEUE_PENDING";
    const INVOICE_REVERSION_STATE_SIN_VALID = "INVOICE_REVERSION_STATE_SIN_VALID";
    const INVOICE_REVERSION_STATE_SENT_TO_SIN_INVALID = "INVOICE_REVERSION_STATE_SENT_TO_SIN_INVALID";
    const INVOICE_REVERSION_STATE_SENT_TO_SIN = "INVOICE_REVERSION_STATE_SENT_TO_SIN";
    const INVOICE_REVERSION_STATE_SIN_INVALID = "INVOICE_REVERSION_STATE_SIN_INVALID";
    const INVOICE_REVERSION_STATE_INTERNAL_ERROR = "INVOICE_REVERSION_STATE_INTERNAL_ERROR";

    const REVERSION_ANULACION_RECHAZADA = 909;
    const ANULACION_RECHAZADA = 906;
    const ANULACION_CONFIRMADA = 905;
    const REVERSION_ANULACION_CONFIRMADA = 907;



    const ARRAY_FINAL_STATUS = [902,904,690,691,906];
    const ARRAY_FINAL_STATUS_EMIT = [902,904,690];
    const ARRAY_FINAL_STATUS_REVOCATE = [691, 906];

    const EMIT_ACTION = 'emit';
    const REVOCATE_ACTION = 'revocate';
    const REVERSION_REVOCATE_ACTION = 'reversion-revocate';

    public static function getFinalStatusArray( $action ) {

        return match( $action ){
            static::EMIT_ACTION => static::ARRAY_FINAL_STATUS_EMIT,
            static::REVOCATE_ACTION => static::ARRAY_FINAL_STATUS_REVOCATE,
            'default' => static::ARRAY_FINAL_STATUS
        };
    }
}